config/authorization/config.ex
draft for CH-core types authorization
=> add authorization types

config/dispatcher/dispatcher.ex
cf kalliope change: added bulk
=> added bulk

docker-compose.yml
Reflects the renaming of the project
=> updated docker image name

docker-compose.yml
This release includes a fix to handle the same triple in the insert and delete part of a single delta msgs and a different bulk upload mechanism. cf docs
=> kalliope api version

config/proxy/web.conf
identical limit to loket and letsencrypt reverse proxy
=> increased max body size

config/proxy/web.conf, docker-compose.dev.yml
@bdevloed  can you also test it with the different kalliope endpoints? i just tested a get with api-docs
=> add basic auth for kalliope & disable it for the rest

config/migrations/202108151011002223444444-create-mock-user.sparql
The current name is confusing since it doesn't sound like a name at all.
=> Use a realistic mock user name

config/migrations/20210830144223-delete-label-from-bestuurseenheid.sparql, config/migrations/20210902170100-rename-location-fusion.sparql
Following the discussion on the ticket https://binnenland.atlassian.net/browse/OP-518
=> Migration to rename the fused locations and remove additional label in Bestuurseenheid

config/migrations/20210906150000-fix-classification-property.sparql
cf https://binnenland.atlassian.net/browse/OP-646
Changed the property via a migration.
=> fix classification property

config/migrations/20210907-psuedonimize.sparql.disabled
Pseudonimization query. disabled by default.
Howto:
- rename file (remove `.disabled`)
- replace `REPLACE_ME_WITH_A_RANDOM_STRING` with a random string. e.g. output of `openssl rand -base64 12`
=> added pseudonimization query. disabled by default.

config/proxy/nginx.htpasswd
rm test config to avoid accidental deployment on QA/PRD
=> rm nginx htpasswd

config/dispatcher/dispatcher.ex
=> removed sparql route

docker-compose.yml
Cookies should have the secure attribute.  Defaulting that in this PR.
=> Set secure cookie option

config/dispatcher/dispatcher.ex, config/resources/domain.json
This functionality is no longer needed.
=> Remove all code related to "verbonden juridische structuren"

config/db/virtuoso-production.ini
Note: virtuoso-production.ini might currently be overkill. Could
consider not using it.
=> Added two tweaked database settings

config/dispatcher/dispatcher.ex, config/migrations/20211119151700-move-reason-codes.sparql, config/resources/domain.lisp, config/resources/privacy-centric-service.json
This can be used to retrieve all the possible options.
=> Add a new `/request-reasons` endpoint

config/dispatcher/dispatcher.ex, config/resources/domain.json
I forgot to remove this in the previous PR.
=> Remove config related to the sensitive data feature

docker-compose.yml
bump including the bugfix related to the countries/gender not being fetched
=> bump privacy service

config/authorization/config.ex, config/dev-migrations/20211209101400-mock-change-events.graph, config/dev-migrations/20211209101400-mock-change-events.ttl, config/dispatcher/dispatcher.ex, config/resources/change-events.json, config/resources/domain.json, config/resources/domain.lisp
This provides the needed backend changes (and some mock data) for the change event functionality.
You can mount the mock data in your docker-compose.override.yml file.
```yml
migrations:
volumes:
- ./config/dev-migrations:/data/migrations/dev
```
=> Change event model updates

config/resources/domain.json
Following comment of Kevin in OP-483
=> fix relationship

config/dispatcher/dispatcher.ex, docker-compose.yml
Related to https://github.com/lblod/jsonld-delta-service/pull/22
=> Remove unused config and bump kallipe-api

docker-compose.yml
Rescheduled to optimize KAL integration (at minute 45 every hr)
=> reschedule op dump creation

config/dispatcher/dispatcher.ex, docker-compose.yml
should be reviewed after:
https://github.com/lblod/privacy-centric-service/pull/3
once the pr for privacy service is merged, todo update the version in docker-compose (the one that is currently there is a local build)
=> sensitive data

config/migrations/2022/20220317100000-remove-bestuurseenheden-op-1075.sparql
Deletes two specific bestuurseenheden mentioned in op-1075
=> Delete bestuurseenheden without status (op-1075)

config/migrations/2022/20220328171923-update-date-change-event-Eeklo.sparql, config/migrations/2022/20220328172743-update-date-change-event-Glabbeek.sparql, config/migrations/2022/20220329114750-remove-kbo-of-Centraal-Comite-van-de-Anglicaanse-Eredienst-in-Belgie.sparql, config/migrations/2022/20220329150729-delete-positions-Protestantse-Kerk-van-Kortrijk.sparql, config/migrations/2022/20220329154322-delete-positions-ckb-staden.sparql
Solves the following incidents : 
- OP-1190
- OP-1191
- OP-1192
- OP-1218
- OP-1249
=> Adds migrations to fix wrong data

docker-compose.yml
will have to be in 1.7.0 as well
=> bump java deps

config/migrations/2022/20220401162146-fix-wrongly-formatted-kbo.sparql
Fix for OP-1273
:warning: To be hotfixed
=> Add migration to reformat weird kbos

config/migrations/2022/20220405084015-delete-triples-pointing-towards-werkingsgebieden.sparql
Forgot to remove those in #114 :grimacing:
=> Add migrations to remove dangling triples

config/migrations/2022/20220406134511-change-status-ckb-melle.sparql
Fixes OP-1282
:warning: Tag v1.7.2 before merging
=> Fix status ckb melle

docker-compose.yml
I already tagged v1.7.3, can you just double check I didn't messed up before I deploy to acc ? Thx :p
=> Hotfix v1.7.3

config/migrations/2022/20220412134535-update-gender-codelist.sparql
OP-1227
No occurences of persons having one of the deleted types, so no need to fix this :)
=> Add migration to update gender codelist

config/migrations/2022/20220414092643-remove-bedinaren.sparql
OP-1307
Merge informations : 
- Tag v1.7.5 before merging
- When deploying, use the following query to update the positions index
```
curl --location --request POST '<search-service-ip-address>/update' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '    [
{
"inserts": [],
"deletes": [
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/613621A7375CFC000A0002C3" },
"predicate": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" },
"object": { "type": "uri", "value": "http://data.lblod.info/vocabularies/erediensten/RolBedienaar" }
},
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/613621A7375CFC000A0002C3" },
"predicate": { "type": "uri", "value": …
```
=> Remove some bedinaren

config/migrations/2022/20220414132656-fix-wrong-resulting-org-after-merge.sparql
OP-1312
Before merge, tag v1.7.6
Use following query to manually re-index the related data : 
```
curl --location --request POST '172.18.0.15/update' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '    [
{
"deletes": [
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/6180d2f3e76d711b9bb0ce5881c5b57d" },
"predicate": { "type": "uri", "value": "http://www.w3.org/ns/regorg#orgStatus" },
"object": { "type": "uri", "value": "http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6" }
},
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/2b871d9f7cf6bec8c2732a8901f23788" },
"predicate": { "type": "uri", "value": "http://www.w3.org/ns/regorg#orgStatus" },
"object": { "type": "uri", "value": …
```
=> Fix change event resulting org and statuses

config/delta/rules.js, docker-compose.yml
=> fix caching issues

docker-compose.yml
see: https://github.com/mu-semtech/mu-cl-resources/releases/tag/v1.21.1
=> bump mu-cl resource for cache clearing fix

config/migrations/2022/20220429135441-remove-person-and-related-positions.sparql
:warning: (for myself) : tag before merge
Hey, can you test it on prod data ? I can't deploy to dev / acc because the issue is only on prod currently, so you'll be the only one to check it before I deploy to prod.
To update the index, you can use the following : 
```
curl --location --request POST '172.18.0.28/update' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '    [
{
"deletes": [
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/mandatarissen/624EE15FD5CA8D65E42B3154" },
"predicate": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" },
"object": { "type": "uri", "value": "http://data.lblod.info/vocabularies/erediensten/EredienstMandataris" }
}
],
"inserts": []
}
]'
```
Thanks !
=> Add migration to remove person and position

config/migrations/2022/20220504081921-fix-missing-governing-body.sparql
OP-1360 (merge to hotfix/v1.7.8)
=> missing governing body

config/migrations/2022/20220518120232-delete-some-positions-Kerkfabriek-H-Maria-van-Boutersem.sparql
=> Add migration to delete some positions

config/migrations/2022/20220518103943-change-status-ckb-aartselaar.sparql
=> Fix CKB status

config/migrations/2022/20220518092941-fix-broken-link-person-position.sparql
=> Add migration to fix broken link person/mandataris

config/migrations/2022/20220602164623-fix-typo-in-position-name.sparql
=> Fix typo in position name

config/migrations/2022/20220718112423-rename-codelist-betrokken-lb.sparql
=> rename code list for bestrokken locale bestuuren

config/migrations/2022/20220816153740-add-vestigingen-types.sparql
=> Add missing site types

config/migrations/2022/20220905103740-delete-primary-when-secondary.sparql
=> cleanup data: delete primary type when it's secondary

config/migrations/2022/20220905205843-add-betrokken-lokale-besturen-to-centrale-besturen.sparql
=> Add betrokken lokale besturen to centrale besturen

config/migrations/2022/20220919100043-fix-status-aalter-voor-fusie.sparql
OP-1765
after tagging, run the following in prod (make sure to change ip address of mu search):
```
curl --location --request POST '172.30.0.13/update' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '    [
{
"deletes": [],
"inserts": [
{
"subject": { "type": "uri", "value": "http://data.lblod.info/id/bestuurseenheden/c895809729a165666fc111a40affe229f3c8e8f1ce9dec2dcc1be1ed81b52d9b" },
"predicate": { "type": "uri", "value": "http://www.w3.org/ns/regorg#orgStatus" },
"object": { "type": "uri", "value": "http://lblod.data.gift/concepts/d02c4e12bf88d2fdf5123b07f29c9311" }
}
]
}
]'
=> Missing status for Aalter voor fusie

config/migrations/2022/20220919140043-delete-site-aalter.sparql, config/migrations/2022/20220919140243-insert-site-aalter.sparql
OP-1775, unfortunately I couldn't do it in one query :(
For the elasticsearch reindexing, it just needs to "bewerk" then "opslaan" each aalter after the migrations ran, and it should trigger reindexing. I asked Sofie if she could do it, as there are only 3 with the problem.
I  struggled with delta message and curly curl today, that wasn't my day
=> duplicate municipality for aalter

config/migrations/2022/20220921140243-change-event-is-city.sparql
=> add stadstitel

config/migrations/2022/20220928133653-adjust-functies.sparql
=> adjust codelist functies

config/migrations/2022/20221007132340-delete-bestrokke.sparql
=> remove bestrokken

config/migrations/2022/20221004164323-uniformize-dates-or-organen-before-2023.sparql, config/migrations/2022/20221005142834-create-missing-mandates-central-worship-organen-2020-2023.sparql, config/migrations/2022/20221005142835-create-missing-mandates-central-worship-organen-2017-2020.sparql, config/migrations/2022/20221005142836-create-missing-mandates-worship-organen-2017-2023.sparql
OP-1822
To be merged after #180 because I base those migrations on the organen dates to filter them properly !
=> Create missing mandates for 2017 to 2023

config/migrations/2022/20221004164323-uniformize-dates-or-organen-before-2023.sparql
revert the merge and reopen the pr
=> Create and uniformize dates or organen before 2023

config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
OP-1696
Has to be tested with https://github.com/lblod/frontend-organization-portal/pull/414 and https://github.com/lblod/construct-administrative-unit-relationships-service/pull/1
=> Add construct-administrative-unit-relationships service and config

docker-compose.yml
=> Fix name search for special characters

config/migrations/2022/20221205161742-update-bedienaar-roles.sparql
OP-1943, OP-1944, OP-1935, OP-1936, OP-1937, OP-1938, OP-1931, OP-1933, OP-1934
=> Change role of some bedienaren

config/migrations/2022/20221222160000-fix-kbo-uris.sparql
cf https://binnenland.atlassian.net/browse/OP-1918
=> fix some kbonrs

config/migrations/2023/20230104152916-delete-orphan-person.sparql
=> delete oprhan persons

config/search/config.json, config/search/dev/config.json, docker-compose.yml
OP-1987
requires a full reindex (sorry)
requires https://github.com/lblod/frontend-organization-portal/pull/430
=> fix missing persons & use standard mu search

.gitignore, config/delta-producer/dump-file-publisher/config.json, config/migrations/2023/20230106140000-publisher-config/20230106143000-delete-old-dump-info.sparql, config/migrations/2023/20230106140000-publisher-config/20230106143000-organization-producer-account.sparql, docker-compose.yml
Draft because conflicts with https://github.com/lblod/app-organization-portal/pull/209
Next steps
1. merge https://github.com/lblod/app-organization-portal/pull/209
2. clean up conficts with this pr
=> organizations publisher config update

config/migrations/2023/20230118093645-fix-non-utf8.sparql
OP-2044 && OP-1915
would be nice to have it for 1.14
=> bugfix non utf8 characters

docker-compose.yml
changed start time to have a bit more margin
=> change start time

config/authorization/config.ex, config/dispatcher/dispatcher.ex, config/migrations/2023/20230119153244-delete-double-betrokken-lokale-besturen-for-cb.sparql, config/migrations/2023/20230119155023-add-missing-betrokken-besturen.graph, config/migrations/2023/20230119155023-add-missing-betrokken-besturen.ttl, config/resources/domain.json
=> Enable local involvements for central worship services

config/migrations/2023/20230118155500-modify-bedienaar-role.sparql
OP-2045 | OP-2046 | OP-2056 | OP-2057 | OP-2060
=> Fix / Change bedienaar roles

config/migrations/2023/20230124100000-delete-person-mandatarissen.sparql
OP-2073
I've recreated the branch from @iurianu  and cherry picked his commit since the previous branch was based on development branch instead of master
=> migration to delete mandatarissen, and person

config/authorization/config.ex, config/dispatcher/dispatcher.ex, config/migrations/2023/20230119153244-delete-double-betrokken-lokale-besturen-for-cb.sparql, config/migrations/2023/20230119155023-add-missing-betrokken-besturen.graph, config/migrations/2023/20230119155023-add-missing-betrokken-besturen.ttl, config/migrations/2023/20230131172200-delete-region.sparql, config/resources/domain.json, config/search-migrations/.gitignore, docker-compose.yml, scripts/project/config.json, scripts/project/mu-search-delta/.gitignore, scripts/project/mu-search-delta/README.md, scripts/project/mu-search-delta/build.sh, scripts/project/mu-search-delta/package-lock.json, scripts/project/mu-search-delta/package.json, scripts/project/mu-search-delta/script.mjs
=> Migration to remove region

config/migrations/2023/20230202100000-change-kbo-number.sparql
=> change kbo number

config/migrations/2023/20230213113324-add-new-codelist.sparql, config/migrations/2023/20230213113324-add-new-position.sparql, config/migrations/2023/20230215094055-add-missing-position.graph, config/migrations/2023/20230215094055-add-missing-position.ttl
=> add new codelist

config/delta-producer/worship-posts/export.json
=> Extend worship posts producer's export config

config/migrations-triggering-indexing/2023/20230227114600-remove-worship-not-actif.sparql
=> Kerkfabriek St.-Antonius van Padua van Gent (Heirnis)

config/dispatcher/dispatcher.ex
OP-2192 (might also fix OP-2186)
=> cache not triggered for related organization

config/migrations/2023/20230418093500-add-org-post-type-to-mandates.sparql
=> Add missing post type

docker-compose.yml
fixes: https://www.vlaanderen.be/digitaal-vlaanderen/nieuwsberichten/gebruikt-u-de-geografische-webdiensten-van-digitaal-vlaanderen-dan-moet-u-actie-ondernemen
=> Bump adressenregister fuzzy search service version

config/delta-producer/public/export.json, config/resources/domain.json
=>  updating end date bestuursorgaan triggers too many deletes

config/migrations/2023/20230504135910-delete-fracties-from-admin-unit-graph.sparql, config/reasoner/dl2op/main-info/query.n3q, config/reasoner/dl2op/main/query.n3q
=> Remove imported fracties and update reasoner config

config/migrations/2023/20230509142503-adjust-change-event.sparql
=> adjust change event

config/migrations/2023/20230616110000-street-and-bus-number-concatination.sparql
=> add missing space

config/migrations/2023/20230622140000-moslimraad.graph, config/migrations/2023/20230622140000-moslimraad.ttl
Add Moslimraad (representatief orgaan)
OP-2490 details in OP-2484
=> added moslimraad

config/migrations/2023/20230703181102-set-executief-van-de-moslims-van-belgie-to-not-active.sparql
=> Add migration updating RO status

config/migrations/2023/20230627110500-add-missing-country.sparql, config/migrations/2023/20230627111000-add-country-to-full-address.sparql, docker-compose.yml
To be deployed together with the FE changes.
=> add country to addresses

config/migrations/2023/20230704112900-onboarding-igs/20230704112912-import-igs-from-loket.graph, config/migrations/2023/20230704112900-onboarding-igs/20230704112912-import-igs-from-loket.ttl
OP-2520
It's hard to test really for now, but if you take the uuid of a bestuurseenheid and paste it in the frontend's URL you can see the KBO and the type showing, and in the organen module we can also see the organen and their dates
Data generated via the following query:
```
CONSTRUCT {
?eenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
<http://mu.semte.ch/vocabularies/core/uuid> ?eenheidUuid ;
<http://www.w3.org/ns/org#classification> ?eenheidClassification ;
<http://www.w3.org/ns/adms#identifier> ?idKbo ;
<http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?werkingsgebied .
?idKbo a <http://www.w3.org/ns/adms#Identifier> ;
<http://mu.semte.ch/vocabularies/core/uuid> ?uuidIdKbo ;
<https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredIdKbo …
```
=> Add migration importing existing IGS data from Loket

config/resources/domain.json
Adds the domain.
Some code lists still need to be added:
- sectors: based on currently used values, to be validated by business
- activities: subset of nacebel - to be defined, which subset
=> added domain.json

config/migrations/2023/20230615161050-remove-municipality-bestrokke.sparql, config/migrations/2023/20230622140000-moslimraad.graph, config/migrations/2023/20230622140000-moslimraad.ttl, config/migrations/2023/20230623103000-moslimraad-fulladdress.graph, config/migrations/2023/20230623103000-moslimraad-fulladdress.ttl
@bdevloed Can we merge this hotfix into the main hotfixes branch for 1.17.3 ?
Subsidiary question, can we also merge 1.17.x into master ? I'm afraid we're gonna have some confusion otherwise when working on master in the next version iteration
=> Hotfix 1.17.3

config/loket-consumer/worship-services-sensitive-dispatching/delta-sync-dispatching.js
=> Variable name worship consumer

config/dev/tlsproxy/Caddyfile, config/dispatcher/dispatcher.ex
To be tested with https://github.com/lblod/frontend-organization-portal/pull/491
=> Remove torii redirect dispatching

config/migrations/2023/20230728170200-add-link-between-uri-and-ovo-uri.sparql
=> Link admin units with OVO uris

config/migrations/2023/20230320135902-onboarding-agb-apb/20230801135516-update-agb-uri.sparql, config/migrations/2023/20230320135902-onboarding-agb-apb/20230801140025-add-missing-organen-and-functies-to-agbs-and-apbs.sparql, config/migrations/2023/20230320135902-onboarding-agb-apb/20230801181808-convert-datetime-to-date-agb-apb-organen-in-time.sparql
=> Fix date format and missing data on AGBs/APBs

config/migrations/2023/20230704112900-onboarding-igs/20230907093015-import-igs-addresses.sparql
=> Add migration to import igs address

config/migrations/2023/20230907133200-fix-double-primary-sites.sparql, docker-compose.yml
=> Fix duplicated primary sites

config/migrations/2023/20230825123000-fix-duplicated-leidinggevenden-values.sparql
OP-2550
based on https://github.com/lblod/app-organization-portal/pull/311 for mandatarissen.
=> cleanup leidinggevenden

config/migrations/2023/20230704112900-onboarding-igs/20230829164552-import-participants-links.sparql
=> Add IGS related organizations

config/migrations/2023/20230704112900-onboarding-igs/20230912112200-fix-igs-iw-classification.sparql
=> Remove wrong classification from IGS IW

config/migrations/2023/20230704112900-onboarding-igs/20230913102813-import-sharepoint-data.sparql
=> Import igs contact data

config/migrations/2023/20230320135902-onboarding-agb-apb/20230824150100-founding-members.sparql
OP-2591
Note: this migration predates on purpose the migration updating the related organizations model on branch `feature/memberships`, to be able to review/deploy faster.
=> Add AGBs and APBs related organizations

config/migrations/2023/20230704112900-onboarding-igs/20230913113222-related-municipalities.sparql
=> Add related municipalities of IGS

config/migrations/2023/20230914154500-onboarding-pz-and-hpz/20230914154600-new-change-event.sparql, docker-compose.yml
OP-2696, OP-2697, OP-2698, OP-2699, OP-2700, OP-2701
=> Onboarding PZ/HPZ - frontend compatibility changes

config/migrations/2023/20230925123100-add-abp-ovos.sparql
=> Insert missing ovo numbers of APBs

config/search/config.json, config/search/dev/config.json
=> Index identifiers for administrative units

config/delta/rules.js, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
OP-2569
To be used with https://github.com/lblod/sync-ovo-numbers-service, which would also need a code review :smile:
=> Set up auto sync of OVO numbers

config/migrations/2023/20231017131126-remove-empty-bestuurseenheden.sparql
=> Remove empty administrative units

config/migrations/2023/20231005111600-onboarding-pz-hvz/20231026092440-add-site-type-hoofdcommissariaat.sparql
=> Add new site type `Hoofdcommissariaat`

config/migrations/2023/20231005111600-onboarding-pz-hvz/20231030074926-import-pz-hvz-addresses.sparql, config/migrations/2023/20231005111600-onboarding-pz-hvz/20231030110742-related-municipalities.sparql
=> Primary sites and related organizations of Politiezones and Hulpverleningszones

config/migrations/2023/20231005111600-onboarding-pz-hvz/20231031091217-import-pz-other-sites.sparql
=> Add hoofdcommissariaat addresses to PZ

config/migrations/2023/20231005111600-onboarding-pz-hvz/20231108142833-import-sharepoint-data.sparql
=> Add contact info PZ & HVZ

config/migrations/2023/20231005111600-onboarding-pz-hvz/20231109160736-extend-contact-details-to-secondary-sites.sparql
=> Propagate contact info to pz secondary sites

config/authorization/config.ex, config/delta-producer/organizations/export.json, config/migrations/2023/20112111524300-fix-typo-bedienaarfinancieringcode.sparql, config/migrations/2023/220231121152430-fix-typo-bedienaarfinancieringcode.sparql, config/resources/domain.json
=> fixed typo

config/dev-migrations/20231104231300-remove-mandatarissen-without-person.sparql
OP-2868
Allows dev to display its data properly before we do a proper fix of the consumer
This migration needs to be followed by a reindex
=> Fix dev mandatarissen without persons

config/authorization/config.ex, config/dispatcher/dispatcher.ex, config/migrations/2023/20231117161347-add-agent-type/20231117161502-organisations.sparql, config/migrations/2023/20231117161347-add-agent-type/20231117161517-people.sparql, config/migrations/2023/20231117161347-add-agent-type/20231117161530-agents-in-position.sparql, config/migrations/2023/20231117161347-add-agent-type/20231123150643-functionaries.sparql, config/migrations/2023/20231117161347-add-agent-type/20231123152046-mandatories.sparql, config/reasoner/dl2op/main-info/mapping.n3, config/reasoner/dl2op/main-info/query.n3q, config/reasoner/dl2op/main/mapping.n3, config/resources/domain.json, config/search/config.json, config/search/dev/config.json
OP-2652
Corresponding [frontend PR](https://github.com/lblod/frontend-organization-portal/pull/541)
Note: requires re-indexing search to work properly
=> Refactor: Introduce generic Agent resource

config/migrations/2023/20231208160845-delete-change-event-lievegem.sparql
OP-2879
The migration needs to be tested against PROD data.
=> Fix: delete unnecessary change event

config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-1.sparql, config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-2.sparql, config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-3.sparql, config/migrations/2023/20231212101609-import-sharepoint-data/20231212101609-import-sharepoint-data-part-4.sparql
OP-2449
See Jira ticket if you're interested in the script used to generate the migration.
=> Import contact data from sharepoint

.gitignore
To avoid thinking we have untracked changes when it's just the new publication triplestore :grin:
=> Ignore publication triplestore data folder

config/migrations/2024/20240115141651-fix-missing-resulting-orgs.sparql
=> fix missing resulting org & betrokke

config/resources/domain.json
=> add site type name attribute

config/delta-producer/organizations-public-info/export.json
=> Exclude the data of CLB from the producer

config/migrations/2024/20240315104123-add-fusion-event-pz-aalter-maldegem.sparql
OP-3067
- The resulting administrative unit "PZ Aalter/Maldegem" is only found in PROD data.
=> Feature: add merge change event pz aalter maldegem

.gitignore, config/migrations-sample/README.md, config/migrations-sample/pseudonimyze-data.sparql-template, config/migrations-sample/remove-stale-jobs.sparql-template, config/migrations-sample/remove-type-in-producer-graph.sparql-template, config/migrations/local/README.md
Copy the `migrations-sample` and `migrations/local` logic in place in Lokaal Beslist.
=> Chore: Add migration template samples

config/delta-producer/organizations-public-info/export.json
This reverts commit 25a5adaf5eafba9502f7183d83fcf9d836055cb9, reversing changes made to c6bb94816d718a1a47ce68bcf9d3583eeac3aece.
#387 was merged too early.
=> Revert "Merge pull request #387 from lblod/feat/exclude-clb-data-from-producer"

docker-compose.yml
=> Chore: bump mu-search version

docker-compose.yml
to make it more digestable for OP (+ search)
=> bump + tweaked ingestion blobs to smaller amounts

config/migrations/2024/20240403104506-remove-empty-alternative-names.sparql
=> fix: remove empty alternative names for administrative units

config/reasoner/dl2op/private-info/mapping.n3
=> fix: add missing prefix

config/dispatcher/dispatcher.ex
=> Remove obsolete kbo-data-sync endpoint

config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
Related to OP-3230
Corresponding frontend PR: https://github.com/lblod/frontend-organization-portal/pull/622
=> refactor: rename construct relationship service

config/migrations/2024/20240604100500-delete-duplicate-identifier.sparql
Related to OP-3157
For some reason, we have duplicate values attached to the same organization. 
Delete all duplicates with a migration
=> Delete duplicate identifier on organization

config/dispatcher/dispatcher.ex, docker-compose.yml
Related to OP-3173
Bump `mu-cl-resources` seems fix the cache problem
=> Fix cache organizations route

config/delta-producer/organizations-public-info/export.json
Related to OP-2897
To merge when sync from OP to CLB will not be needed anymore.
=> Remove CLB data from the producer

config/delta-producer/organizations-public-info/export.json
Add org classification to op-public producer (and some auto code format changes)
=> export representative organ classification

config/delta-producer/organizations/export.json, config/delta-producer/public/export.json, config/delta-producer/worship-posts/export.json
add classification to public producer used by loket (previous was org-public)
=> export ro classifcation in other public producer too

config/migrations/2024/20241011105932-link-bestuursfunctie-to-public-producers-concept-scheme.sparql
See: https://github.com/lblod/app-organization-portal/pull/456
This is a cherry-picked version of the PR, as the original started from `development`-branch which would take too long to get deployed.
=> Link missing classifications to public producer concept scheme

config/delta-producer/organizations/export.json, config/delta-producer/public/export.json
Required predicate for leidinggevenden.
=> Added missing predicate: `lblodlg:heeftBestuursfunctie`

config/migrations/2024/20241023123140-add-end-dates-bestuursorganen.sparql
Adds end dates to bestuursorganen
=> Added migration to add end-dates to bestuursorganen

config/migrations/2024/20241028125621-remove-functionarissen-newly-created-organen.sparql
They have another lifecycle than political mandates.
=> Removes the newly created bestuursorganen for leidinggevenden

config/delta-producer/public/export.json, config/migrations/2024/20241105095234-add-classification-to-abb-as-bestuurseenheid.sparql
ABB should also be exported as bestuurseenheid.
=> Added config export to export ABB

config/delta-producer/organizations-public-info/export.json, config/delta-producer/public/export.json
=> update RO - concept to export

config/migrations/2024/20241202142000-cleanup-worship-data/20241202142000-remove-betrokken-lokaal-bestuur-nieuwerkerken.sparql, config/migrations/2024/20241202142000-cleanup-worship-data/20241202143000-remove-test-kerk-nijlen.sparql
Fixes 2 tickets in PRD:
- betrokken lokaal bestuur: https://binnenland.atlassian.net/browse/OP-3491
- test kerk created in PRD: https://binnenland.atlassian.net/browse/OP-3488
=> remove wrong data in prd

config/migrations/2024/20241218115931-add-missing-werkingsgebieden-ocmw.sparql
It seems OCMW's were the only ones without werkingsgebied. And the corresponding gemeente had this.
=> Added missing werkingsgebied for OCMW.

CHANGELOG.md, docker-compose.yml
DL-6490
Some services are missing docker compose keys.
=> Add missing `logging` keys for some services

CHANGELOG.md, config/delta-producer/public/export.json
Sorry for yet again a PR on the producer, while testing I noticed I forgot to produce secondary sites as well :sweat_smile: 
I didn't add any extra changelog because it's fully included in the previous notes.
=> Produce secondary sites in public producer as well

CHANGELOG.md, config/migrations/2025/20250430144720-update-date-change-event-ckb-olen.sparql
OP-3594
Update date of a change event of ckb olen to '30-11-2023'.
=> Fix: update change event date of ckb olen

CHANGELOG.md, config/migrations/2025/20250729143008-kbo-startDate-modified-date-to-dateTime.sparql, docker-compose.yml
- Added a migration to change (only for KboOrganisaties) all dates/strings for modified and startDate to dateTime according to comment in ticket
- Added a comment to remind to bump version of kbo-data-sync when the kbo-data-sync PR is merged.
- Added to changelog (no deploy command since restart migations is already in there)
[OP-3560](https://binnenland.atlassian.net/browse/OP-3560)
=> OP-3560 Fix Kbo organisations date formats
