lblod/app-organization-portal

- .env.example
- .gitignore
- docker-compose.dev.yml
- docker-compose.prod.yml
- docker-compose.yml
This
- doesn't restart the services while developing
- doesn't start the basic auth check service while developing
- adds a .env.example file
> Docker compose config updates

- docker-compose.prod.yml
This pins the frontend image to the v0.2.0 release. Future releases will require a version bump here as well.
The dev environment has already been updated to use the latest tag instead.
> Pin the frontend image to a specific tag

- docker-compose.dev.yml
It seems the triplestore key was listed twice and the second one overrode the first version, so the service would be restarted automatically.
> Don't restart the triplestore service in dev

- config/migrations/20210909152600-fix-percentage-sort-part-1.sparql
- config/migrations/20210909152630-fix-percentage-sort-part-2.sparql
It seems that something in the Semantic Works stack doesn't handle sorting values with the xsd:floats type properly. The frontend receives the records in the wrong order.
Explicitly converting the floats to a xsd:decimal solves the problem so we use that as a workaround for now.
> Make sure financing percentages are sorted as expected

- config/migrations/20211001-meta.ttl
Adding the hierarchy to enable more elegant sparql queries. i.e. use the subclass information to query for all possible bestuurseenheden.
> bestuurseenheid hierarchy

- config/frontend/add-x-frame-options-header.conf
- docker-compose.yml
We don't want these pages to be contained in a frame.  The x-frame-options serves that use.
To my understanding, it's fine if this is executed for all html pages.  Any attack would need to confuse people, and hence would need them to be visit a page.  Hence this is the right place to my understanding.  Feel free to verify that assumption.
> Add x-frame-options when hosting frontend pages

- docker-compose.dev.yml
I noticed some services didn't have the auto restart disabled in the dev config.
> Prevent services from restarting in development

- config/resources/change-events.json
- config/resources/domain.json
If only the date is relevant we should not store it as a `datetime` since that would add timezone information which might cause the date to be displayed incorrectly in the frontend.
> Use `date` instead of `datetime` were needed

- config/migrations/2022/20220125185900-rename-change-event-result-relationship-predicate.sparql
- config/resources/change-events.json
- config/resources/domain.json
This relationship uses the same `org:organization` predicate that is also used for the local involvements relationship. When querying for local involvements data when an organization also has change events data,  mu-cl-resources receives the change events data instead and runs into errors. This is likely a bug in the micro service itself. Renaming the predicate is a quick workaround so we have more time to find the real solution for the problem without a broken app.
> Temporarily rename the change-event-result organization relationship

- docker-compose.yml
Compresses the ttl dumps at rest.
Concretely, files in the data/files/delta-producer-dumps/dump-organizations are now gzipped.
OP-API remains unchanged.
> use compressed dumps

- config/dev-migrations/20210910120000-pseudonimize-UPDATE-BEFORE-RUNNING.sparql.disabled
This prevents Virtuoso cancelling queries which take too much time
> Optimize query performance - avoid thread kill

- docker-compose.yml
bugfix for OP-1284. 
No reindex needed, just test if you can still edit a person & a bestuur
> fix regression mu search

- config/dispatcher/dispatcher.ex
fix OP-1394.
How to reproduce:
-  create a new bestuur (worship service)
- create a new position (bedinaer) with a new person
- once saved, click on edit the bedinaer then click annuleer
- => the position disappears from bedinaer
- refresh the page, the position is lost unless you restart the cache
Checkout the branch:
- do the same as above
- the position doesn't disappear now
> disable cache for worship services

- config/migrations/2022/202206131O4623-normalize-space.sparql
OP-1495:
For some reasons there are few remainings after script runs, but it should be just a few.
```sparql
select ?o ?normalize  where {
graph <http://mu.semte.ch/graphs/organisatieportaal> {
?s ?p ?o.
BIND (replace(str(?o), "^(\\s+)|(\\s+)$", "") as ?removeTrailingSpace).
BIND (replace(?removeTrailingSpace, "\\s{2,}", " ") as ?normalize).
filter(isLITERAL(?o) && (regex(?o, "\\s{2,}") || regex(?o, "^(\\s+)|(\\s+)$")) )
} 
}
```
> normalize spaces

- config/migrations/2022/20220719112423-update-toezicht.sparql
**new definition:**
Toezichthouder: Kan slechts 1 gemeente/provincie zijn per eredienstbestuur. Dit is de hoofdgemeente/provincie zodat duidelijk is waarnaar de notulen moeten gezonden worden, wie de andere gemeentes/provincies moet betrekken etc. Bij de orthodoxe en de islamitische besturen zal hier dus de naam van een provincie moeten staan en niet de naam van een gemeente. Bijkomend wordt er een financieringspercentage vermeld.
**data changes:**
there are 119 worship services that have this relationship more than one. The local municipality that isn't the main "toezichthouder", need to get the role "mede-financierend" assigned.
**how to test**
- with prod data, this one seems to correspond to a case:
http://localhost:4200/bestuurseenheden/77fd7b2aeb6bcb3f7d80db6e25a98e41/betrokken-lokal …
> update toezicht with new definition

- config/migrations/2022/20221004164323-uniformize-dates-or-organen-before-2023.sparql
OP-1821
This one is a bit tricky, I tried to check on multiple ways that it was correct but can you double check ? :sweat_smile: 
Here is a small query I used to control my results, it gives the options of start / end dates of organen:
```
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
SELECT DISTINCT ?start ?end WHERE {
GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
VALUES ?type {
ere:BestuurVanDeEredienst
ere:CentraalBestuurVanDeEredienst
}
?bestuurseenheid a ?type .
FILTER NOT EXISTS {
?bestuurseenheid <http://www.w3.org/ns/regorg#orgStatus> …
```
> Create and uniformize dates or organen before 2023

- config/migrations/2022/20221209093743-add-missing-betrokken-besturen.graph
- config/migrations/2022/20221209093743-add-missing-betrokken-besturen.ttl
I noticed that on the Loket side of the apps, some links have been added to be able to dispatch properly data to graphs (see [here for example](https://github.com/lblod/app-worship-decisions-database/blob/master/config/migrations/2022/20221110165132-add-missing-betrokken-besturen.ttl) ). This PR is adding the same data to keep the apps in sync. It'll also be useful for app-worship-organizations.
See DL-4442 for the context
> Add missing betrokken lokale besturen links

- config/migrations/2023/20230106110000-delete-duplicate-worship-services.sparql
The migration was removing all the contact points, all the addresses and all the identifiers of the database.
It's important to order the optionals correctly, each optional is a distinct block and what happens in an optional block stays in the optional block. So a variable defined in an optional block can't be reused outside of this block.
> Update migration to avoid data loss

- config/migrations/2023/20230118153000-delete-empty-literals.sparql
OP-1329
No new empty literals should be created
- frontend has been adapted (OP-1331)
- loket consumers retract empty literals
No re-index triggers needed
> delete empty literals

- config/delta-producer/dump-file-publisher/config.json
- config/migrations/2023/20230119164500-cleanup-files.sparql
cf OP-2069
Work around bug in dump-file publisher when deleting old dumps https://github.com/lblod/delta-producer-dump-file-publisher/pull/6
> use same graph for dcat and files to avoid bug

- config/migrations-triggering-indexing/2023/20230203150000-remove-dummy-worship.sparql
- config/migrations/2023/20230203150000-remove-dummy-worship.sparql
- docker-compose.dev.yml
- docker-compose.yml
OP-2117
I used a [currently ongoing PR](https://github.com/lblod/app-organization-portal/pull/234) to test wiring mu-migrations to mu-auth to see how would the reindexing work in our stack. And as a first test, it looks conclusive !
I wired it as a separate service because our previous migrations are full of comments and maybe other things that mu-auth does not like. So if we would go to having just one migrations service, we'd have to also clean older migrations to ensure that the project would be able to run from an empty DB. And I think that it doesn't hurt to keep it as a second service for now, gives us more time to try it out and see how the auto-reindexing goes.
It also means that now, before starting `migrations-triggering-indexing`, some services should be up for the changes to …
> Migrations triggering reindex

- config/dispatcher/dispatcher.ex
My previous attempt here https://github.com/lblod/app-organization-portal/pull/240 was not enough because before getting the file we try go get the dataset & distributions and we get outdated info. Restarting the cache fixes the issue. So I think that now with this change we'll be fine :crossed_fingers:
> Remove cache from dcat resources

- config/migrations-triggering-indexing/2023/20230324150743-update-status-and-orgaan-of-st-egidius-van-sint-gillis-waas.sparql
- docker-compose.yml
OP-2231 & DL-4980
I also had to bump mu-search, I was getting HTTP 500 errors otherwise (`NoMethodError - undefined method `each' for nil:NilClass`). I also had to restart the cache after the search's trigger.
About the mandates creation:
- LidVanRechtswege : shared mandate for all the organen in time
- Bestuursleden big half : shared with 2023-2026 because 2020 was the start of a big half
- Bestuursleden small half : new mandate (should have been shared with 2017-2020, but we don't have this time period)
- Voorzitter : new mandate
- Secretaris : new mandate
- Penningmeester : new mandate
> Fix status and add missing orgaan

- config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327162800-merge-organen.sparql
- config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327162900-create-missing-organen-in-time-2023-2026.sparql
- config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327163000-create-missing-positions-central-worship-services-2023-2026.sparql
- config/migrations/2023/20230327162700-prepare-change-legislation-period/20230327163000-create-missing-positions-worship-services-2023-2026.sparql
- docker-compose.yml
OP-2241
In this PR we:
- Update config variables to create worship organen in the new legislation period on worship service creation
- Fix oddities in the bestuursorganen (organen that needed to be merged, missing organen, missing mandates)
> Enable new period for organen and create missing data

- config/migrations/2023/20230503143253-organen-start-and-end-should-be-datetimes-part-one.sparql
- config/migrations/2023/20230503143421-organen-start-and-end-should-be-datetimes-part-two.sparql
- config/resources/domain.json
OP-2308
The migration goes in two parts because, for some reason, changing the type doesn't work when the date = the datetime exactly, so I use a subterfuge where I put a datetime slightly different from the date (1h different :sweat_smile: ) and put it back in a second migration.
> Ensure organen dates are datetimes

- config/migrations/2023/20230330164600-sync-loket-to-op/20230330164606-remove-ministers-that-will-get-synced.sparql
OP-2326
This story of ministers, positions, ministers positions ... It's getting everybody confused, me included apparently :sweat_smile: 
In the previous migration, I removed the theoretical positions (`PositieBedienaar`) instead of the real position (aka the person in the position at a certain time, `RolBedienaar`).
It only got deployed on dev, so I restored the missing data on dev directly (using Loket as a source, as it was in sync). This migration should now only delete what's necessary, no more.
Deploy note: when deploying this fix to dev, it will also remove already-synced ministers as the initial sync has already run. We'll have to re-trigger an initial sync (should be fine as positions can't be edited in OP anymore). For QA and Prod,  no problem as the wrong migration didn't run …
> Fix migration removing too much data

- config/delta/rules.js
- config/dispatcher/dispatcher.ex
- docker-compose.dev.yml
- docker-compose.yml
OP-2364
The [delta-producer-json-diff-file-publisher](https://github.com/lblod/delta-producer-json-diff-file-publisher) service has been archived and can fully be replaced by using only [delta-producer-publication-graph-maintainer](https://github.com/lblod/delta-producer-publication-graph-maintainer).
> Remove deprecated delta-producer-json-diff-file-publisher service

- config/delta/rules.js
- docker-compose.yml
OP-2400
As the LDES feed it's not ready yet to be used on QA or PROD, to simplify the release process, we add a profile to the related services to disable it by default.
To enable it on dev, we just have to run the following command: `docker-compose --profile dev up` and mount a delta config including the ldes rules.
> Add dev profile to ldes feed

- docker-compose.yml
This PR updates the `redpencil/fragmentation-producer` to version 0.3.3 which includes a fix for situations where feed members were incomplete
> Update ldes-backend image to 0.3.3

- docker-compose.dev.yml
- docker-compose.yml
This PR updates the ldes-backend image to 0.4.0. 
This update includes some breaking changes, as it is now required to pass a `BASE_URL` environment variable to the service.
The service uses `BASE_URL` to resolve its relative URLs.
I included the `BASE_URL` env var in `docker-compose.dev.yml`, set as `http://localhost/ldes/`.
> Update ldes-backend image to 0.4.0

- config/migrations/2023/20230712152618-igs-link-positions-to-unit-classifications.sparql
- config/reasoner/dl2op/main/query.n3q
- docker-compose.yml
OP-2513
For testing, it's a little bit tricky as we miss some data. I took some notes that you can reuse !
```
Test with leidinggevenden of Stadsregio Turnhout
Can not be tested the right way because we are missing too much data (primary sites data + labels of ISG)
So by adding this extra data, we'll at least be able to test for the leidinggevenden of ONE bestuur to see if the code
works or not. We add a label and an existing primary site, to make our lifes easier :)
INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
<http://data.lblod.info/id/bestuurseenheden/7cab1a9c6f5dc798164f1c6812fc790e5279a8fe7800a2e8b7a159c581c866f1>
skos:prefLabel "Stadsregio Turnhout" ;
<http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/e215e097cd2f054c9de6db80cf34 …
```
> Add IGS positions to the sync

- config/ldes-delta-pusher/dispatch.ts
This PR includes a change to the `dispatch` function of the ldes-delta-pusher. For each organization sent to the LDES feed, the local identifiers and labels for each of their identifiers is also included.
- Set-up the stack
- Create/edit and organization and include some identifiers
- Check if the ldes-feed has been updated with the new information on `/ldes/organizations/1`, the new information will be included on the last page of the feed.
The structure sent to the LDES-feed is a bit complicated, maybe we can use other predicates to link the KBO/OVO numbers to the organizations directly instead of through the `local-identifier`/`structured-identifier` predicates?
> Include local-identifier and label for each identifier of organizations sent to ldes feed

- docker-compose.yml
Pointed out by Niels, we were missing some restart statements in the docker-compose configuration
> Add missing restart statements

- config/migrations/2023/20231005111600-onboarding-pz-hvz/20231005111611-pz-hz-from-Loket.graph
- config/migrations/2023/20231005111600-onboarding-pz-hvz/20231005111611-pz-hz-from-Loket.ttl
- config/migrations/2023/20231005111600-onboarding-pz-hvz/20231005111625-import-pz-and-hvp.graph
- config/migrations/2023/20231005111600-onboarding-pz-hvz/20231005111625-import-pz-and-hvp.ttl
OP-2703
Requires a reindex to be able to see the PZ and HVZ admin units in the search page !
Note that we are still missing data, mostly the addresses, the related organizations and the contact information.
> Import PZ & HVZ basic data

- config/search/config.json
- config/search/dev/config.json
OP-2725
This change allows to fix a bug where units with identifiers containing special characters such as dashes or brackets where not correctly included in the results.
> Fix: add an alphanumeric only index field for identifiers

- config/migrations/2023/20231107175200-fix-vast-bureau-concept.sparql
OP-2819
<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/55ab0e9b8a3b2ca7c5e000008> uri has been wrongly introduced via migrations in OP.
Before just removing it, let's assess its impact.
We'll check the impact in OP itself as well as in Loket, which consumes part of OP's data
The real uri is missing some triples, that we wrongfully linked to the wrong uri:
```
http://mu.semte.ch/graphs/public 	http://www.w3.org/2004/02/skos/core#inScheme 	http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b
http://mu.semte.ch/graphs/public 	http://www.w3.org/2004/02/skos/core#inScheme 	http://data.vlaanderen.be/id/conceptscheme/BestuursorgaanClassificatieCode
http://mu.semte.ch/graphs/public 	http://www.w3.org/2004/02/skos/core#topConceptOf …
```
> Fix vast bureau concept data

- config/migrations/2023/20231124220109-remove-mandataris-without-person.sparql
OP-2867
As the impact is very limited (one mandataris) and it has been like this for a while without anybody noticing I think we can wait for the next release to merge it, hence the merge to the dev branch. It'll require a reindex, but that will be the case anyways with the onboarding of new admin units.
> Remove mandataris without person

- config/delta-producer/dump-file-publisher/config.json
- config/delta-producer/organizations-public-info/export.json
- config/delta/rules.js
- config/dispatcher/dispatcher.ex
- config/jobs-controller/config.json
- config/publication-triplestore/virtuoso-production.ini
- config/publication-triplestore/virtuoso.ini
- docker-compose.dev.yml
- docker-compose.yml
OP-2875
In this PR, we add a new producer called `organizations-public-info`. It is basically a copy of the `public` producer, without the restrictions to only produce worship organizations data. This one produces a wider range of data that will first be used by the CLBV team for their applications and then, in a second phase, will replace the `public` producer in Loket as well.
We also introduce a new triplestore to the application, the `publication-triplestore`. This is inspired by Loket and the issues they had there when they started to have multiple producers graph in the main triplestore, slowing down a lot the main triplestore and consequently the application. To avoid getting the same issues in OP, let's try to anticipate!
> Add publication triplestore and organizations public info producer

- docker-compose.yml
Updated [construct-administrative-unit-relationships-service](https://github.com/lblod/construct-administrative-unit-relationships-service) to v0.1.6 which includes a fix for OCMW verenigingen.
> Bump construct-administrative-unit-relationships-service

- docker-compose.yml
Without those placeholder values, on a stack where those variables are not added in the override, the delta notifier becomes extremely slow because it can't reach the sharepoint sync service (that crashed because those essential variables were missing).
With this trick, at least the stack doesn't freeze if locally the variables are not overridden.
> Add placeholder variables to prevent deltanotifier being slow

- config/migrations/2022/20220719112423-update-toezicht.sparql.disabled
- config/migrations/2022/20220819133740-delete-bestrokke-islam-orthodox.sparql
- config/migrations/2022/20220822133740-delete-bestrokke.sparql
- config/migrations/2022/20221007132340-delete-bestrokke.sparql
- config/migrations/2022/20221015132000-delete-bestrokken-besturen-hemiksem.sparql
- config/migrations/2022/20221015134000-delete-bestrokken-besturen-ronse.sparql
- config/migrations/2022/20221019174000-delete-bestrokken-besturen-anglican.sparql
- config/migrations/2022/20221222160000-fix-kbo-uris.sparql
- config/migrations/2023/20230616110000-street-and-bus-number-concatination.sparql
- config/migrations/2023/20230627110500-add-missing-country.sparql
- config/migrations/2023/20230627111000-add-country-to-full-address.sparql
- config/reports/utils.js
This prefix has wrongly been defined with https instead of http in some places. Luckily, it has no impact on the data because everywhere where it has been defined that way, it also never has been used. So here we just rectify the (unused) prefixes to avoid bringing further confusion.
Note: we really just update older migrations for the sake of not confusing devs that would ctrl+F to find that prefix, the migrations will not re-run.
> Replace https by http in lblodlg prefix

- config/migrations/2024/20240108134546-onboarding-peva/20240108134546-onboarding-peva-classification-code-peva-gemeente.sparql
- config/migrations/2024/20240108134546-onboarding-peva/20240108134610-onboarding-peva-classification-code-peva-provincie.sparql
- docker-compose.yml
Adds new classification codes for PEVA municipality and PEVA province which will be onboarded in OP-2640. These new classification codes are specifically defined in the context of OP and are not (yet) part of the upstream standard. 
Frontend PR: https://github.com/lblod/frontend-organization-portal/pull/558
> Feature: Added new classification codes for PEVAs

- config/migrations/2024/20240130152459-maldegem-combine-merger-change-events.sparql
OP-2973
Note, this additional PR was created to allow a hotfix release with the same migration as reviewed in #372.
> Fix: combine multiple incorrect merger change events into a single one change event

- config/dev-migrations/20240201000000-remove-ocmw-association-wieltjesgracht.sparql
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240212141020-import-public-ocmw-associations-loket.graph
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240212141020-import-public-ocmw-associations-loket.ttl
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140142-import-public-ocmw-associations.graph
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140142-import-public-ocmw-associations.ttl
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140143-missing-organen-and-functies-for-ocmw-associations.sparql
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140212-import-public-ocmw-association-addresses.sparql
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140236-import-public-ocmw-association-contact-details.sparql
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240216175509-import-public-ocmw-association-founders.sparql
These migrations add the data for public OCMW associations, this contains the core data, primary site data, contact details, and some boilerplate necessary to correctly model such organisations in OP.
Relevant tickets:
- OP-2947 for address data
- OP-2948 for contact details
- OP-2979 for related organisations
This data does **not** contain:
- Functionaries (will be synced from Loket)
- Change events
- Finding the new organisations via the search functionality in the fronted requires re-indexing.
- Not all organisations have a SharePoint identifier
- Ter Lembeek has no KBO number, it will be added later by business.
- A zip-file containing all used data files and scripts can be found in OP-2540.
- For related organisations only founding organisations are added at this point
This migration …
> Feature: Import data for public OCMW associations

- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215151233-import-pevas.graph
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215151233-import-pevas.ttl
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215151234-create-governing-bodies-for-pevas.sparql
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215151701-import-peva-addresses.sparql
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240215152042-import-peva-contact-details.sparql
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240219094948-import-peva-founders.sparql
The newly added migrations import the data for organisations of classification PEVA municipality and PEVA province into our app. The data concerned for each organisation is its core data, primary site information, contact details, along with boilerplate necessary to store this according to our data model.
Relevant tickets:
- OP-2953 for addresses
- OP-2954 for contact details
- OP-2980 for related organisations
- These types of organisations are currently **not** in Loket.
- No PEVA currently has s SharePoint identifier.
- Finding the new organisations via the frontend requires re-indexing, they are readily accessible via their URL.
- A zip-file containing all data files and scripts used, can be found attached to OP-2640.
The migration is spread over several files each imported part of …
> Feature: Import data for PEVA municipality and PEVA province

- docker-compose.yml
Updating the `mu-cl-resources` service to the lasted in order to resolve bugs such as the one reported in OP-2940.
> Chore: bump mu-cl-resources to latest version

- config/authorization/config.ex
- config/migrations/2024/20240226102340-copy-name-to-legal-name.sparql
- config/resources/domain.json
- config/search/config.json
- config/search/dev/config.json
OP-2999
- Add a `legal-name` attribute to organisations
- For existing organisations, initialise this new attribute with the value of `skos:prefLabel` via a migration
- Include this new attribute in the search index
> Feature: add legal name for organisations

- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240306133508-fix-ocmw-associations-provinces.sparql
- config/migrations/2024/20240214133210-onboarding-peva-data-import/20240306132750-fix-peva-provinces.sparql
OP-3062 and OP-3063
In the initial migrations the province was incorrectly set to the same value as the municipality for OCMW associations as wll as PEVAs. These new migrations first remove the incorrect province and then insert the correct value.
- These migrations are generated using a script so each query is identical except for the concrete values such as KBO number and province. It is thus not necessary to go through all the queries in the migrations.
- The province column on the index page will still display the old, incorrect values. Updating these requires a reindexing. The province shown on the core data page should display the new, corrected value.
> fix: set correct value for provinces of OCMW associations and PEVAs

- config/migrations/2024/20240311134000-import-pz-hvz-names/20240311151100-delete-existing-alternative-names.sparql
- config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161908-import-politiezone-juridical-names.sparql
- config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161909-import-politiezone-alternative-names.sparql
- config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161910-import-hvz-juridical-names.sparql
- config/migrations/2024/20240311134000-import-pz-hvz-names/20240311161911-import-hvz-alternative-names.sparql
OP-3087
Added (generated) migrations to import the juridical and alternative names for PZs and HVZs as provided by business.
- PZ = Politiezone = Police zone
- HVZ = Hulpverleningszone = Assistance zone
- This PR is branched from #390 to simplify working with alternative names. Correctly displaying alternative names requires using https://github.com/lblod/frontend-organization-portal/pull/586 for the frontend. 
- Displaying the newly imported juridical names in the index table requires re-indexing.
> Feature: Import juridical and alternative names for PZ and HVZ

- config/migrations/2024/20240318142001-add-new-recognized-worship-types.sparql
- config/migrations/2024/20240318144801-update-missing-types-representative-bodies.sparql
"Boeddistisch" and "Niet-confessioneel" are added as recognized worship types for 2 new representative organs that had no type of worship service.
Change can go paired with typo fix "Boeddistiche" to  "Boeddistische" because change requires Re-Indexing
related PR: https://github.com/lblod/app-organization-portal/pull/398
> Adding 2 new recognized worship types

- config/migrations/2024/20240313141034-worship-Lochrist-remove-local-involvement.sparql
OP-3036
This migration removed all predicates concerning the local involvement of municipality Lokeren in the worship service Kerkfabriek St.-Eligius van Lochristi (Zeveneken).
> fix: remove superfluous local involvement

- docker-compose.yml
Bumped the 3 consumers to the latest version of the `delta-consumer`. It should be backwards compatible but some testing/monitoring seems prudent.
> chore: bumped consumers to latest version

- config/delta-producer/organizations/export.json
Related to OP-2957, OP-3128
This PR contains modifications required by Kalliope consumer.  
- add `http://data.vlaanderen.be/ns/besluit#Bestuurseenheid`
- add website (`http://xmlns.com/foaf/0.1/page`) in ContactPoint
- add `http://www.w3.org/ns/prov#Location` (the glue between administrative-unit with NISCODE)
> Add administrative-unit in delta-producer/organisations

- config/delta-producer/organizations/export.json
- config/delta-producer/public/export.json
- config/delta-producer/worship-posts/export.json
Following #406 this adds the legal and alternative names to the exports for all other consumers.
Notes:
- The alternative name was previously already included in most exports.
- I do not think the consumers of our data require immediate changes to keep up to date data. The frontend will update the value for `skos:prefLabel` whenever a user changes an organisation's `regorg:legalName`.
> feat: export legal and alternative names via producers

- config/migrations/2024/20240415085335-correct-representative-body-classification-code-type.sparql
For representative body classification codes there was an inconsistency between our `mu-cl-resources` configuration and the actual type object stored in the triplestore.
Our `domain.json` specifies as `ext:RepresentatiefOrgaanClassificatieCode` as class for `representative-body-classification-codes`. While the stored triples specified `ext:RepresentatieveOrgaanClassificatieCode` as type. This error was introduced in #342. The new migration corrects the type in the triplestore.
An alternative solution would be to change our `domain.json` but "representatief orgaan" is the correct term in Dutch we use through the app.
> Fix: correct type for classification to match resource configuration

- config/clb-consumer/contact-data/delta-sync-dispatching.js
- config/clb-consumer/contact-data/util.js
This lowers down the problematic delta from 200k insertions to "only" 2k. Still takes a lot of time because of the cascade queries we make, but there's no solution for that yet according to Boris.
Also this deltas will be removed in the future from CLB as they are an error so we won't have this problem, but anyway this makes the consumer more perfomant overall
> avoid inserting duplicate triples to the database

- config/delta-producer/background-job-initiator/config.json
- config/delta-producer/dump-file-publisher/config.json
- config/delta-producer/publication-graph-maintainer/config.json
- config/delta/rules.js
- config/dispatcher/dispatcher.ex
- config/jobs-controller/config.json
- config/migrations/2024/20240429105000-clear-producer-organizations-graph.sparql
- docker-compose.dev.yml
- docker-compose.yml
- Bump `lblod/delta-producer-background-jobs-initiator` to v1.0.1
- Bump `lblod/delta-producer-publication-graph-maintainer` to [v1.1.1-rc.1](https://github.com/lblod/delta-producer-publication-graph-maintainer/pull/31/files)
- Refactor `delta-producer-background-jobs-initiator` and `delta-producer-publication-graph-maintainer` configuration 
- Use `publication-triplestore` instead of the main `triplestore` to store the producer graph
Related to OP-3151
> Fix prefLabel missing in Kalliope dump after edition  

- config/migrations/2024/20240429134438-remove-dangling-change-event-results.sparql
OP-3168
The change events related to an organisation contains some data errors:
- There is a change event result without any corresponding change event. This
causes an error when visiting the change events page for this organisation.
- There are two identical change event results for the same change event. This
causes the change event to be shown twice in the table. (Only on PROD)
The added migration removes these unnecessary elements change event results.
Note: it may be required to also restart the cache service before you correctly
see the result of this migration. Without a restart the same error and duplicate
entries kept popping up in the frontend for me.
> fix: remove dangling change event results

- config/dispatcher/dispatcher.ex
- docker-compose.yml
The new version of the service bring 2 fixes : 
- fix the rewrite of all `fullAddress` https://github.com/lblod/sync-wegwijs-organization-service/pull/8
- fix the rewrite of `sameAs` on KBO organization https://github.com/lblod/sync-wegwijs-organization-service/pull/7
Do not use the old version when feature flag is false is needed to prevent the `sameAs` override.
> Fix kbo-data-sync rewrite all `fullAddress` and override `sameAs`

- config/dispatcher/dispatcher.ex
- config/resources/domain.json
- config/search/config.json
- config/search/dev/config.json
OP-3142
Corresponding frontend: [PR 602](https://github.com/lblod/frontend-organization-portal/pull/602)
- Moved the classification relationship from `administrative-units` to `organizations` and generalised its target to `organization-classification-codes`.
- Rename the `units` index in the search configuration to `organizations` to indicate it covers more than administrative units. (Which it already did since it includes representative bodies.)
- Dispatch requests on the `organizations` path directly to the `resources` service instead of the `cache` service
> Refactor: generalise backend for non-administrative unit organisations

- config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240517135033-ter-lembeek-import-participants.sparql
- config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240517154632-import-public-ocmw-association-participants.sparql
OP-3040
- The used business data can be found in the excel linked in OP-3037. This PR only concerns the data in the "VVMV_participants_public" sheet.
- The migration was generated using a python script that can be found in the ZIP file in a comment in ticket OP-2540. The script is located in the subfolder "05-related-organisations".
- The migration for "Ter Lembeek" was manually adapted from the generated one as the business data does not contain a KBO number for this organisation.
> feat: import participants for public OCMW associations

- config/authorization/config.ex
- config/dispatcher/dispatcher.ex
- config/resources/domain.json
- config/search/config.json
- config/search/dev/config.json
OP-3186
The necessary service (configurations) are extended to handle a new type of organization: Registered organizations (nl. Geregistreerde organisaties). An example of such organizations are the private OCMW associations.
- For registered organizations the dispatcher routes directly to the `resources` service instead of the `cache` due to OP-3173.
- The actual migrations importing the data for private OCMW associations will be added in a separate PR.
- The actual classifications codes were already imported previously in #367 
- The `construct-administrative-unit-relationships-service` itself was previously already extended with the necessary classification codes, see https://github.com/lblod/construct-administrative-unit-relationships-service/pull/8 (A follow-up ticket to …
> Feature: support registered organisations

- config/dev-migrations/20240522095345-public-ocmw-associations-remov-participants.sparql
- config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522120919-ter-lembeek-import-participants.sparql
- config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522123045-import-public-ocmw-association-participants-part1.sparql
- config/migrations/2024/20240517134134-public-ocmw-associations-related-organizations/20240522123045-import-public-ocmw-association-participants-part2.sparql
The initial version of these migrations introduced in #423 were defined too
broadly. Since they only matched on KBO numbers they also included the KBO
organisations, imported from wegwijs, adding them as participants.
This PR fixes these issues by
- Removing the previously imported data using a DEV-specific migration
- Add additional `FILTER` statements to exclude KBO organisations
- Split the main migration into two parts to work around an error otherwise
encountered when executing the migration in one go
> fix: exclude KBO organisations as participants

- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140212-import-public-ocmw-association-addresses.sparql
- config/migrations/2024/20240212141020-onboarding-public-ocmw-associations/20240215140236-import-public-ocmw-association-contact-details.sparql
- config/migrations/2024/20240603115300-correct-agb-address-and-contact-data/20240603115306-fix-agb-address-data.sparql
- config/migrations/2024/20240603115300-correct-agb-address-and-contact-data/20240603133736-fix-agb-contact-data.sparql
OP-3252
The two migrations introduced in #379 that import address and contact data for
public OCMW associations contained a faulty query matching on an empty KBO
number. Consequently, incorrect address and contact data was associated with
some AGB that do not have a KBO number either.
Since the original migrations only inserted new data, the original data is still
present in the triplestore. Therefore, the migrations simply remove the
incorrect data. Additionally, for addresses the correct value for
`locn:adminUnitL2` is (re-)inserted as these was overwritten.
Some SPARQL queries I used while analysing the problem and to verify whether the migrations work as expected:
Get the address information for the primary site of the affected AGBs.
``` sparql
$prefixes
SELECT DISTINCT ?name ?addr ?p …
```
> Remove faulty address and contact data for AGBs

- config/dispatcher/dispatcher.ex
We cannot use cache on `kbo-organizations` route, because data are updated by `lblod/sync-wegwijs-organization-service` and the cache will be never invalidated.
> Disable cache on `/kbo-organizations/*`

- config/migrations/2024/20240529155230-add-other-classification-codes.sparql
- docker-compose.yml
Related to OP-3023
Add classifications for new types of organizations: associations (*nl. verenigingen*) and corporations (*nl. vennootschappen*). These classifications are intended for internal use in OP to allow extending the app with these new organizations without having the fundamentally revise it. Our frontend, for instance, heavily uses classifications to show the correct fields in forms etc.
- frontend: https://github.com/lblod/frontend-organization-portal/pull/628
- construct-organization-relationships-service: https://github.com/lblod/construct-organization-relationships-service/pull/14
> feat: added classification code for associations and corporations

- config/migrations/20240619123310-remove-kbo-organizations-from-participation-relation.sparql
OP-3286
The migration importing related organizations for public OCMW associations was
incorrect in that it did not exclude resources of type `ext:KboOrganisatie`
being matched. This migration removes all incorrectly inserted triples.
The incorrect migration was originally added in #423 and an initial fix for the
same issue was proposed in #425. The fix was also incorrect as it added a filter
on the participant resource instead of the association resource, which is the
resource that can be of the incorrect type.
> fix: remove `org:memberOf` triples with KBO organizations as object

- config/migrations/2024/20240718152515-worship-services-alternative-names-part1.sparql
- config/migrations/2024/20240718152515-worship-services-legal-names.sparql
- config/migrations/2024/20240718152516-worship-services-alternative-names-part2.sparql
OP-3115
Adds a migration to import the legal and alternative names for worship services.
- Any existing legal name is first removed.
- The alternative name queries check whether there exists a `skos:prefLabel`
triple for the resource to avoid inserting names for non-exiting organizations
(in DEV or QA).
- Any already existing alternative names, inputted by the users, are not
modified or deleted.
- Deployment:
- Also restart the cache (and resources) service to ensure the changes
immediately show up for all organizations.
- Perform full reindex
comments ticket.
> feat: import legal and alternative names for worship services

- .gitignore
- config/kalliope/security-dev.json
- config/kalliope/security-dev.yml
- docker-compose.dev.yml
- docker-compose.yml
Related to OP-3172
This is a preparation to bump kalliope-api to the new javascript implementation. 
TODO:
> Bump kalliope-api to 2.0.0

- docker-compose.yml
There was an issue with the old producers not taking into account all graph filters, thereby exporting sometimes too many triples.
Note: please consider moving these old producers to the latest one. (It should be a matter of shuffling config around)
seeAlso: DL-5911
Can this be first merged in master and then merged in development?
> Bump old producers, from 0.15.4 -> 0.15.5

- config/migrations/2024/20240827145640-merged-district-borsbeek.sparql
The municipality of Borsbeek will merge with the municipality Antwerp as of
01-01-2025. This will result in a new district Borsbeek part of municipality
Antwerp.
This migration adds that new district such that a URI is assigned to it and its
governing bodies are created. The data provided by business:
- name: "Borsbeek"
- legal name: "Borsbeek"
- organisation classification: "District"
- Status: "In oprichting"
- KBO number: districts use the same KBO number as their municipality, therefore
OP does not add a value for their KBO numbers
- required Governing bodies (period 2025 - ...):
+ Districtsburgemeester
+ Districtsraad
+ Districtscollege
OP-3381
> feat: add new district Borsbeek

- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160204-timed-governing-bodies-gemeente-2025.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160205-timed-governing-bodies-ocmw-2025.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160206-timed-governing-bodies-district-2025.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160207-timed-governing-bodies-provincie-2025.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160208-add-missing-governing-bodies-merged-ocmw-beveren_kruibeke_zwijndrecht.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160209-add-missing-governing-bodies-merged-ocmw-merelbeke_melle.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160210-add-missing-governing-bodies-merged-ocmw-nazareth_de_pinte.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829160211-add-missing-governing-bodies-merged-ocmw-pajottegem.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171504-mandates-burgemeester.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171505-mandates-gemeenteraad.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171506-mandates-college_van_burgemeester_en_schepenen.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171507-mandates-voorzitter_van_het_bijzonder_comite_voor_de_sociale_dienst.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171508-mandates-raad_voor_maatschappelijk_welzijn.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171509-mandates-vast_bureau.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171510-mandates-bijzonder_comite_voor_de_sociale_dienst.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171511-mandates-provincieraad.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171512-mandates-gouverneur.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171513-mandates-deputatie.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171514-mandates-districtsraad.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171515-mandates-districtsburgemeester.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171516-mandates-districtscollege.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171539-functions-algemeen_directeur.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171540-functions-adjunct-algemeen_directeur.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171541-functions-financieel_directeur.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171542-functions-adjunct-financieel_directeur.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171543-functions-griffier.sparql
- config/migrations/2024/20240828104739-governing-bodies-mandates-2025-legislation/20240829171544-functions-financieel_beheerder.sparql
In preparation for the new legislature for local governments, OP requires new time specialised governing bodies, along with their mandates and functions. This concerns organisations with the following classifications:
- municipality
- OCMW
- district
- province
The migrations added by this PR create the necessary data. The added migrations can be roughly divided in three groups which must be executed in the listed order:
- `TIMESTAMP-timed-governing-bodies-CLASSIFICATION-2025.sparql`: add the necessary time specialised governing bodies for (almost all) active organisations of the above classifications
- `TIMESTAMP-add-missing-governing-bodies-merged-ocmw-NAME.sparql`: add some extra governing bodies to OCMWs that were missing in their initial import in #442
- …
> feat: add governing bodies, mandates, and functions for 2025 legislature

- config/migrations/2024/20240903164444-remove-duplicate-uri-for-ibeg.sparql
DL-5770
This PR adds a migration to remove a duplicate organization URI, its properties + reverse properties and its connected bestuursorganen and bestuursorganen in tijd.
> Remove duplicate URI for IBEG

- config/migrations/2024/20240905164200-remove-https-BestuurseenheidClassificatieCode.sparql
**[OP-3335]**
These is some data referring to both the HTTPS and HTTP variant of the BestuurseenheidClassificatieCode entity. The HTTPS variant does not exist elsewhere and is to be removed.
> Remove HTTPS BestuurseenheidClassificatieCodes

- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241009143404-delete-contact-data-modified-in-clb.sparql
- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241009161800-clb-prod-contactdata-administrative-units.graph
- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241009161800-clb-prod-contactdata-administrative-units.ttl
- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241009161900-clb-prod-contactdata-worship.graph
- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241009161900-clb-prod-contactdata-worship.ttl
- config/migrations/2024/20241009143404-update-contact-data-from-clb/20241011132019-fix--remove-spaces-in-phone-number.sparql
These migrations add the contact data from CLB production that was modified in
that app during the time it was available. These migrations perform the
following actions, in the specified order:
1. Delete all contact data for the 8 modified sites
2. Import the data extracted from CLB production for the relevant organisations
Done in separate migrations for worship and non-worship organisations.
3. Correct a phone number literal that contained spaces for some reason
These migrations are the same as those mentioned in #457 to be executed as local
migrations on PROD. Since the migrations do not contain private it was decided
to treat them as regular migrations anyway.
Background information on how these migrations were created can be found in …
> feat: import most recent CLB data

- config/migrations/2024/20241018111200-add-type-bestuurseenheid-to-centrale-besturen.sparql
According to the model they should be `besluit:Bestuurseenheid`.
> Added migration to add besluit:Bestuurseenheid to centrale besturen

- config/delta-producer/dump-file-publisher/config.json
The dump-file-publisher was still fetching data from the wrong store. Now that everything is moved to the publication triplestore.
> DumpfilePublisher needs to fetch from publication-triplestore

- config/migrations/2024/20241022120000-add-type-bestuurseenheid-to-eredienstbestuurseenheid.sparql
It seems somehow  (in QA) `besluit:Bestuurseenheid` was removed for a significant amount of `ere:BestuurVandeEredienst`. The cause is unsure; what is sure though; is that all `?types` should correctly be added.
> Ensure types and subtypes are added to EredienstBestuurseenheid

- config/migrations/2024/20241024103653-delete-incorrect-links-between-apbs-and-municipalities.sparql
A number of APBs were accidentally `org:linkedTo` all municipalities in municipality and an APB for which:
- the APB is linked to more than 1 municipality; and
- the municipality does not match that of the APB's primary site.
The first condition avoids we remove `org:linkedTo` triples for APBs that were created by the users, as these are only linked with a single municipality.
Notes:
- I opted not to use the URIs of the APBs so this migration works on all environments.
- On QA there are 4 APBs created for testing that do not have a site and will  thus not be fixed by this migration. On PROD this situation does not occur.
- This PR is against the master branch in order to include it in the next hotfix (1.27.4). Otherwise. the membership functionality, part of the next full release …
> fix: delete superfluous relations between APBs and municipalities

- config/migrations/2024/20241023075148-delete-change-event-dodoens.sparql
A user entered a faulty change event, this migration removes it again.
Note: the change event is only present in the production data.
OP-3363
> fix: remove incorrect change event

- docker-compose.yml
Bump the following services to the most recent versions:
- identifier to v1.10.3
- migrations and migrations-triggering-indexing to v0.9.0
- resource to v1.25.0
- file to v3.4.0
The versions bumped to do not introduce breaking changes or changes requiring additional changes.
> chore: bump services

- config/migrations/2024/20241211101235-align-skos-notation-identifier.sparql
It seems there were language tagged and non-languaged versions used for the skos:notation from ADMS:identifier.
This migrations alings it, we don't want typed strings here. See also DL-6343
> Fix skos:notation ADMS:identifier language tags

- config/migrations/2024/20240916161553-remove-organizations/20240916161554-remove-limgrond-be-data.sparql
- config/migrations/2024/20240916161553-remove-organizations/20240918143141-remove-intercommunale-maatschappij-opera-voor-vlaanderen-data.sparql
- config/migrations/2024/20240916161553-remove-organizations/20240918220856-remove-fluvius-data.sparql
- config/migrations/2024/20240916161553-remove-organizations/20240918221021-remove-intercommunaal-samenwerkingscomite-van-waterbedrijven-data.sparql
- config/migrations/2024/20240916161553-remove-organizations/20240918221245-intercommunale-van-brabant-voor-gas-data.sparql
- config/migrations/2024/20240916161553-remove-organizations/20240918221637-tussengemeentelijke-electriciteitsvereniging-van-kampenhout-en-steenokkerzeel-data.sparql
OP-3124 + OP-3125
This PR deletes organization URIs (+ other related URIs) as this data is deemed to be unneeded.
The best way to test this would be:
* Tunnel to production, use `DESCRIBE <bestuurseenheid_URI>` and follow the links.
* Do a quick skim between the URIs connected to the bestuurseenheid URI and cross-check with the queries.
The cross-checking part is a bit annoying, but there aren't many resources attached to these organizations, so it should be fairly quick.
> Add queries to remove organizations

- config/migrations-triggering-indexing/2024/20241126155527-rename-merged-municipalities-and-ocmws.sparql
As part of the 2025 municipality mergers 3 municipalities, and their
corresponding OCMWs, keep their original URI but do change their name. More
specifically:
| Current name | Name after merger |
| ------------ | ----------------- |
| Bilzen       | Bilzen-Hoeselt    |
| Ham          | Tessenderlo-Ham   |
| Tongeren     | Tongeren-Borgloon |
- OP-3456
> chore: rename municipalities and OCMWs for mergers 2025

- config/migrations/2024/20241203090835-mergers-2025-add-end-dates-governing-bodies-merged-organisations.sparql
Set the end date for governing bodies for municipalities and OCMWs that are
involved in a municipality merger **and** will become inactive afterwards.
For the municipalities and OCMWs that remain active after the merger, the end
date has already been set previously.
- Run the added migration
- Via the frontend:
+ Go to the governing bodies page for a relevant organisation
(they are listed in the `VALUES` clause in the migration's query)
+ Check whether the end date for the governing bodies that start in 2019 is
set to 02/01/2025
- The status of the governing bodies is automatically determined in the frontend
based on the start and end dates. So no explicit status changes are required.
- OP-3412 contains an overview of which organisations are involved in mergers
and which ones …
> feat: set end date governing bodies for merged organisations

- config/migrations-triggering-indexing/2024/20241203144827-mergers-2025-update-organisation-status.sparql
- config/migrations/2024/20241203112740-mergers-2025-add-merge-change-events/20241203112740-mergers-2025-add-merge-change-events-results-are-new-organisations.sparql
- config/migrations/2024/20241203112740-mergers-2025-add-merge-change-events/20241203141834-mergers-2025-add-merge-change-events-results-are-existing-organisations.sparql
- config/migrations/2024/20241203112740-mergers-2025-add-merge-change-events/20241203164934-mergers-2025-antwerp-and-borsbeek.sparql
These migrations insert the merger change events that are needed for the 2025 municipality mergers and update the status of the appropriate organisations. These mergers involve municipalities, OCMWs, and 1 new district.
This migration involves mergers where the resulting organisation is different from the original organisations. This concerns mergers involving the organisation added in #442. This situation is the same as for the previous municipality mergers (see #365).
This migration involves mergers where the resulting organisation is one of the original organisations. In this case there is only one change event result for organisation that is both an original and resulting organisation.
This migration handles the special case of the merger of Borsbeek and Antwerp. For the …
> feat: add merger change events for 2025 municipality mergers

- config/migrations-triggering-indexing/2024/20241217082404-mergers-2025--update-addresses/20241217082404-change-zwijndrecht-to-province-east-flanders.sparql
- config/migrations-triggering-indexing/2024/20241217082404-mergers-2025--update-addresses/20241217082944-update-address-municipality-to-merged-municipality-name.sparql
- config/migrations-triggering-indexing/2024/20241217082404-mergers-2025--update-addresses/20241217083314-regenerate-full-address-triple-for-changed-addresses.sparql
As part of the 2025 municipality mergers the address for a number of organisations changes. This PR updates the municipality names in the addresses for affected organisations and, for organisations located in Zwijndrecht, also updates the province. Additional updates such as street name, building number, or box number are left up to the users.
The migrations in this PR perform the needed address changes in three steps:
1. Change the addresses located in municipality Zwijndrecht from the province of Antwerp to East Flanders.
2. Change the municipality for all addresses located in a municipality whose names change as part of a merger:
| Original municipality name | Merged municipality name     |
|----------------------------|------------------------------|
| Borsbeek                   | …
> chore: Update addresses for 2025 municipality mergers

- config/migrations/2024/20241212201809-remove-empty-uris-received-by-kalliope.sparql
OP-3426
The Kalliope team notified us of empty URIs they received; these URIs only have `http://www.w3.org/1999/02/22-rdf-syntax-ns#type` and `http://mu.semte.ch/vocabularies/core/uuid` properties attached to them. So, they can be safely deleted.
Run the migration and make sure these URIs no longer have any data.
> Remove empty URIs

- config/migrations/2025/20250107100000-nis-codes-2025/20250107101800-refnis2025.graph
- config/migrations/2025/20250107100000-nis-codes-2025/20250107101800-refnis2025.ttl
- config/migrations/2025/20250107100000-nis-codes-2025/20250107102500-add-uuids-to-nis-codes-2025.sparql
- config/migrations/2025/20250107100000-nis-codes-2025/20250107103200-update-nis-codes-to-2025-update.sparql
- config/migrations/2025/20250107100000-nis-codes-2025/20250107104100-link-new-fusie-gemeenten-to-their-nis-codes.sparql
OP-3342
To follow up with the addition of mergers in OP, we want to add their NIS codes as well into the app. A (new version)[https://github.com/belgif/vocab-belgif/blob/master/prod/data/codelist/refnis2025.nt} of the NIS codes has been created to reflect the state of 2025.
This PR does a few things:
1. Import the 2025 NIS codes
2. Update our `werkingsgebieden` to link to 2025 NIS codes when an exact match is found between the version of 2019 and the one of 2025
3. Add a link from `werkingsgebieden` to 2025 NIS codes for the mergers
The non-mergers should still look the same as before in the frontend but the data should be using mostly 2025 NIS codes.
The mergers should show the following NIS codes:
|                    Fuserende gemeenten                   |           Nieuwe gemeenten …
> Import 2025 NIS codes and update werkingsgebieden

- config/migrations/2025/20250108143939-fix-municipality-mergers--move-province-hassuborganization-to-shared-graph.sparql
For worship users the province was is automatically filled in forms when one of
4 merged municipalities is selected. Furthermore, when a province is selected in
a form these same 4 municipalities do not show up as valid options for
municipality fields. The 4 affected municipalities are: Nazareth-De Pinte,
Beveren-Kruibeke-Zwijndrecht, Merelbeke-Melle, and Pajottegem.
In #442 new organisations were created for these municipalities. But their
`org:hasSubOrganization` link with the province was inserted in to the
`<http://mu.semte.ch/graphs/administrative-unit>` graph instead of the
`<http://mu.semte.ch/graphs/shared>`. As can be seen in the last `INSERT` query
in each municipality's migration.
Since worship users cannot read from the `administrative-unit` graph, any
queries concerning the …
> fix: relate merged municipalities and province in shared graph

- config/migrations-triggering-indexing/2025/20250108194417-mergers-2025-police-zones--deactivate-merged-organisations.sparql
- config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108184654-mergers-2025-police-zones--tongeren-borgloon-herstappe-heers-wellen.sparql
- config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108190240-mergers-2025-police-zones--beveren_kruibeke_zwijndrecht-sint_gillis_waas-stekene-temse.sparql
- config/migrations/2025/20250108184340-mergers-2025-police-zones/20250108193811-mergers-2025-police-zones--vlaamse-ardennen.sparql
A number of police zones merge together, resulting in 3 remaining active police zones. All organisations were already created by business, this PR only add the merger change events and updates the necessary organisation statuses.
More concretely the following police zones are involved:
| Original organisations                             | Resulting organisation                                         |
|----------------------------------------------------|----------------------------------------------------------------|
| PZ Alken/Borgloon/Heers/Kortessem/Wellen           | PZ Tongeren-Borgloon/Herstappe/Heers/Wellen                    |
| PZ Tongeren/Herstappe                              |                                                                | …
> feat: merge police zones 2025

- config/migrations/2025/20250108154325-delete-local-involvements/20250108154325-delete-local-involvement-borsbeek.sparql
- config/migrations/2025/20250108154325-delete-local-involvements/20250108154750-delete-local-involvement-meulebeke.sparql
- config/migrations/2025/20250108154325-delete-local-involvements/20250108154850-delete-local-involvement-hoeselt.sparql
OP-3512
Remove 3 local involvements of 'borsbeek', 'meulebeke' and 'hoeselt'.
Note that I didn't update the financing values, as the ticket described that it will be done in the frontend.
Rsync prod data, run migration and verify that the local involvements are removed.
> cleanup local involvements

- config/migrations/2025/20250107101243-delete-local-involvement-oudenaarde-st-amandus.sparql
OP-3501
Remove the betrokken bestuur of St-Amandus, 'Oudenaarde'. And update the financierings percentage to 100 for the other betrokkene 'Wortegem-Petegem'.
Rsync prod data, run migration and verify that the betrokken bestuur (Oudenaarde) is removed, and the other betrokkene (Wortegem-Petegem) has a percentage of 100.
> Migration to delete betrokkene and update financieringspercentage

- .gitignore
- config/migrations-triggering-indexing/local/README.md
Add support for environment-local migrations that trigger indexing. This is
similar to local migrations for the regular `migrations` service are placed in
the `config/migrations/local/` folder.
> feat: allow local migrations that trigger indexing

- CHANGELOG.md
- config/migrations-triggering-indexing/2025/20250109200145-archive-agb-stekene.sparql
OP-3409
A previous PR only updated the org's status to `Inactive`. However, we should now delete all data related to it as Loket doesn't have a notion of `status`, which can lead to issues.
Tunnel to the database and go over the forward and reverse connections to this organization. After running the migration, all data should be deleted.
> Note: I left the comments in the migration for the purpose of separating the components and making it easier to have a look at what is going to be deleted. The comments will be removed once the PR is approved since `mu-auth` doesn't accept them.
> Completely remove AGB Stekene's data

- CHANGELOG.md
- config/migrations-triggering-indexing/20250114093158-fix-merger-change-event-sint_martinus-st_amandus.sparql
The worship service the worship organisation *St.-Amandus* was not included as `orginalOrganization` in its merger change event. As a result it was not listed as involved organisation in the change event details. Furthermore, its status was not correctly updated to "Not active".
The new migration corrects the relevant change event by adding a link to the worship organisation and updating the organisation's status.
- Restart the correct migrations service, see command in the changelog.
- Verify that
+ The status of *St.-Amandus* has changed to "Niet actief"
+ The merger change event should now list *St.-Amandus* as involved organisation.
The URIs of the relevant resources can be found in the ticket and the migration itself.
- Should be tested with PROD data
- The index updates may take …
> fix: merger change event between St.-Amandus and Sint-Martinus

- CHANGELOG.md
- config/search/config.json
- config/search/dev/config.json
Index municipality names as keywords instead of as plain text. This prevents them from being split at word separators. Thereby avoiding that searches for a municipality name, as used by the frontend's municipality filter, return organisations whose municipality is a partial match.
For example, previously the results when searching for "Puurs" also included the organisations located in "Sint-Amands-Puurs". The latter was tokenized into three terms, therefore also matching plain "Puurs". By treating the municipality name as keyword this split non longer happens.
1. Boot up a local OP stack
2. Open up the frontend and login as a user, a non-worship role is the most convenient
3. On the organisations overview page, use the municipality (*nl. Gemeente*) filter in the sidebar to limit the …
> fix: index municipality names as keywords instead of regular text

- scripts/reset-elastic.sh
This makes the `reset-elastic.sh` script more flexible by automatically determining whether to use `docker-compose` or `docker compose`. The script now essentially checks the exit status for `docker compose version`. If that command executes successfully use `docker compose`, otherwise fall back to `docker-compose`.
Furthermore, this replaces the `--remove-orphan` flag in the last command by `--remove-orphanS`, which was introduced in [v1.7.0](https://docs.docker.com/compose/releases/release-notes/#170). I was unable to find when the singular variant `--remove-orphan` was introduced or removed.
It is possible to take a more fine-grained approach by extracting the version numbers from the output of `docker compose version` and/or `docker-compose --version`, for instance using `sed` with an …
> refactor: determine docker compose command based on system

- CHANGELOG.md
- config/migrations/2025/20250129125705-remove-bcsd-bestuursorganen-faciliteitsgemeenten.sparql
OP-3535
OCMWs for Voeren and 6 facility municipalities should not have a Bijzonder comité voor de sociale dienst.
> Add migration to remove bcsd

- docker-compose.yml
This adds example entries for `DCR_SYNC_LOGIN_ENDPOINT` and `DCR_SECRET_KEY`
environment settings for the worship consumers. The example value for
`DCR_SYNC_LOGIN_ENDPOINT` was chosen to match the value for `DCR_SYNC_BASE_URL`.
These environment settings need to be set correctly for both
consumers. Including examples in the `docker-compose.yml` makes this more
explicit.
> chore: additional example environment settings for worship consumers

- CHANGELOG.md
- config/migrations/2025/20250220171921-move-status-for-municipalities-and-provinces-to-shared-graph.sparql
For new frontend functionality concerning local involvements a worship user
should be able to read the status for municipalities and provinces. This
migration moves these triples to the `shared` graph such worship users have read
access.
The status for municipalities and provinces cannot be changed by users so they
do not require write access. The status of these types of organisations can only
be changed manually via migrations, for example when municipalities merge as was
done in #482. This PR makes the situation for statuses essentially the same as
was already the case for the (legal) names for municipalities and provinces.
This should not impact:
- The produced data as the producers already take the `shared` graph into
account.
- The search indexes as this is based on the access …
> chore: move status for municipalities and provinces in shared graph

- CHANGELOG.md
- config/migrations/2025/20250225102801-agb-update-governing-bodies-new-legislature/20250225102801-insert-end-dates-agb-governing-bodies.sparql
- config/migrations/2025/20250225102801-agb-update-governing-bodies-new-legislature/20250225112043-insert-timed-governing-bodies-new-legislature.sparql
The governing bodies for AGBs follow the legislative period of their corresponding municipality. For the new legislature no new corresponding time-specialised governing bodies were created. This resulted in complaints from vendors that AGBs could not link dossiers to the *correct* governing bodies.
Add new timed governing bodies for all AGBs for the current legislature and set the end date for the governing bodies for the previous legislature. More specifically this concerns the governing bodies with classifications *Raad van bestuur* and *Algemene vergadering*.
The set start and end dates were provided by business in the follow-up ticket.
Follow the instructions added to the changelog and check that:
- all AGBs now have an inactive and active *Raad van bestuur* and *Algemene vergadering* …
> fix: add governing bodies for AGBs for the new legislature

- CHANGELOG.md
- config/db/virtuoso-production.ini
- config/db/virtuoso.ini
- config/publication-triplestore/virtuoso-production.ini
- config/publication-triplestore/virtuoso.ini
- docker-compose.yml
Fixes OP-2492 and OP-3547
This is a routine database upgrade that bumps it to the most recent stable build of `virtuoso`. This bump also fixes weird sorting behavior (you can find more info on this in the tickets listed above).
The upgrade steps are laid out [here](https://github.com/Riadabd/upgrade-virtuoso).
> Upgrade `triplestore` and `publication-triplestore` to `v1.3.0-rc.1`

- CHANGELOG.md
- config/delta-producer/public/export.json
- config/migrations/2025/20250325131100-add-public-producer-concept-scheme-to-nis-codes.sparql
[CLBV-980]
We want to stop using the `organizations-public-info` gradually. For that, in `app-contactgegevens`, we need the public producer to produce the NIS codes (which are public so it fits with the description :) ). This is what this PR does.
**_Update_**: we also need the countries there, it's a codelist and OP is the master of it so it makes sense to also produce it I think.
On a running stack:
```
drc restart migrations delta-producer-publication-graph-maintainer 
drc exec delta-producer-background-jobs-initiator curl -X POST http://localhost/public/healing-jobs
```
And check that the produced deltas are containing the NIS codes and the countries.
> Produce NIS codes and countries in public producer

- CHANGELOG.md
- config/migrations/2025/20250409115500-reset-kbo-organization-modified-to-resync.sparql
- docker-compose.yml
[OP-3584]
To be tested with https://github.com/lblod/sync-wegwijs-organization-service/pull/9
Follow the changelog for testing instructions! The idea is to set the "modified" date of the KBO organizations extremely far in the past so that they will be updated again with the proper data types. Once the healing ran, you should be able to see statuses again in the frontend.
> Add migration and instructions to reset kbo sync

- CHANGELOG.md
- config/migrations/2025/20250416181230-fix--refnis-2025/20250416181230-refnis2019-after-2025-municipality-mergers.graph
- config/migrations/2025/20250416181230-fix--refnis-2025/20250416181230-refnis2019-after-2025-municipality-mergers.ttl
- config/migrations/2025/20250416181230-fix--refnis-2025/20250416182754-fix--update-refnis2019-end-dates.sparql
- config/migrations/2025/20250416181230-fix--refnis-2025/20250416184331-refnis2019-flush-temp-graph.sparql
- config/migrations/2025/20250416181230-fix--refnis-2025/20250417080910-fix--update-narrowed-or-broadened-werkingsgebieden.sparql
The NIS2025 codes were initially introduced in #490. This PR resolves two small oversights in that initial import.
Several NIS2019 were given an actual end date to indicate that they are no longer valid after the 2025 municipality merger. This PR updates the relevant end dates based on the most recent version of the NIS2019 code list. This way we know which NIS codes are no longer valid.
The used migration essentially replaces all of OP's NIS2019 code end dates that differ from those on the most recent version code list, and replaces them by the latter. Note that this covers more than just the NIS2019 affected by the 2025 municipality mergers.
As part of the 2025 municipality mergers, the (former) municipality of Zwijndrecht changed province from Antwerp to East Flanders. This change is …
> fix: update NIS2019 end dates and link werkingsgebieden

- CHANGELOG.md
- config/migrations/2025/20250430174011-chore--move-memberships-from-shared-to-administrative-unit-graph.sparql
These memberships can be edited by users via the related organizations page. If
this data is kept in the, read-only, shared graph it leads to unexpected
behaviour when users (try to) remove such a membership. More specifically, as
the user has no write acces to the graph the request will be silently ignored
and the "removed" data will simply reappear after saving the data.
Furthermore, when a user adds similar memberships via the frontend they will be
added to the administrative-unit graph. Over time this can lead to an unexpected
and confusing distribution of memberships over graphs.
> chore: move memberships from shared to administrative-unit graph

- CHANGELOG.md
- config/delta-producer/organizations/export.json
- config/delta-producer/public/export.json
- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250430142110-chore--move-werkingsgebieden-to-public-graph.sparql
- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250430145904-fix--relate-district-location-to-municipality.sparql
- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250430153558-feat--add-werkingsgbied-for-borsbeek-district.sparql
- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250430180050-feat--relate-werkingsgebieden-for-municipalities-and-provinces.sparql
This PR cleans up the existing location (*nl. werkingsgebieden*) data in preparation for adding functionality to view and edit them in OP. More specifically the migrations do the following:
1. Move all existing locations to the `public` graph. Previously the locations were largely duplicated in the `shared` and `adminsitrative-unit` graphs. I opted to put them in the `public` graph instead of in the `shared` graph as the existing locations are essentially a "standard" set that should not change over time. (Except in rather rare circumstances such as municipality mergers.)
2. Add the missing location for the district of Borsbeek. This was overlooked when creating the new district in #445
3. Add `geo:sfWithin` relations between the different location levels:
a. Link all district locations …
> chore: cleanup location data

- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250430180050-feat--relate-werkingsgebieden-for-municipalities-and-provinces.sparql
- config/migrations/2025/20250430130307-chore--cleanup-werkingsgebieden-data/20250521102551-fix--move-location-triples-from-shared-to-public.sparql
In #542 the data related to locations was (supposed to be) moved to the `public` graph. Yet the migrations in the original PR contained two errors.
First, the migration[^1] adding the link between municipality and province locations incorrectly inserted the new data in the `administrative-unit` graph. This migration is fixed as part of the current PR.
The initial migration was already executed on DEV, so that environment will require executing an additional local migration to correct the data. I opted to modify the original migration instead of adding a new one so that on QA and PROD the data is immediately inserted in the correct graph.
``` sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX prov: <http://www.w3.org/ns/prov#>
DELETE {
GRAPH ?g {
?s geo:sfWithin ?o .
}
} …
```
> fix: insert location relations in the correct graph

- CHANGELOG.md
- config/migrations-triggering-indexing/2025/20250520103521-update-status-kerkfabriek-weelde.sparql
- config/migrations-triggering-indexing/2025/20250520110719-update-status-protestantse-kerk-oostende.sparql
- config/migrations/2025/20250520105233-delete-change-event-oostende.sparql
- config/migrations/2025/20250520110017-update-date-change-event-islamic-association.sparql
OP-3602, OP-3604 and OP-3598
This PR bundles the datafix of 3 different orgs/tickets for PROD data:
- update status kerkfabriek weelde [OP-3598]
- delete change event and update status protestantse kerk oostende [OP-3604]
- update change event date islamic assocation [OP-3602]
Setup stack with prod data, verify for each ticket that the desired change is done
> fix: datafix of 3 orgs

- docker-compose.dev.yml
- docker-compose.yml
The version property has been deprecated for a while. Now that the servers are on a recent version of docker compose these can be removed from our configurations. This avoids that the warnings are shown each time. The version property should also be removed from the `docker-compose.override.yml` files on the individual environments. 
Additionally, the `networks` entry in each environment's override file can be changed from
```yml
networks:
proxy:
external:
name: letsencrypt_default
```
to its equivalent
```yml
networks:
proxy:
name: letsencrypt_default
external: true
```
This gets rid of the other deprecation warning we receive.
> chore: remove deprecated version from docker compose configurations

- CHANGELOG.md
- config/migrations-triggering-indexing/2025/20250619113048-fix--rename-locations-merged-municipalities-that-kept-uri.sparql
As part of the 2025 municipality mergers, three municipalities kept their URI
but were renamed. This updates the labels for their scope of
operation (nl. werkingsgebied) locations accordingly. This way the label of the
location resources matches the name of the municipality administrative unit.
- I added this as a migration triggering indexing such that the appropriate deltas are created and the changes can be propagated to consuming apps with having to wait (or trigger) a healing job.
> fix: update label for locations to match their merged municipality

- CHANGELOG.md
- config/migrations-triggering-indexing/2025/20250607150000-brussels-gewest/20250625163700-add-brussels-as-municipality.sparql
- config/migrations-triggering-indexing/2025/20250607150000-brussels-gewest/20250625163800-add-brussels-as-municipality.sparql
[OP-3628]
In a previous PR we added Brussel as a province. This PR extends it a bit and adds the corresponding municipality. It also brings the city title change event and the link between the municipality and the province (implying that conditional filters should work in the main organizations page)
Make sure the stack is up and running before running the migration. Then
```
drc restart migrations-triggering-indexing
```
Gemeente Brussel should be found via the index, it should have all the properties given by Sofie in the ticket. We should also be able to pick Brussel as a city when manually entering an address, for a site for example.
> Add brussel municipality via migration

- CHANGELOG.md
- config/resources/domain.json
This includes an organisation's URI in the response from the resource
service. This allows to easily get the URI for an organisation without having to
determine it based to UUID and classification and/or explicitly querying the
triplestore.
This is mostly a convenience for developers, but can be leveraged to add a link
to Centrale Vindplaats in the frontend.
- Should be tested and deployed with this [frontend PR](https://github.com/lblod/frontend-organization-portal/pull/682)
> feat: include URI in responses for organisations

- CHANGELOG.md
- config/migrations/2025/20250704104058-feat--add-agb-havenbedrijf-antwerpen.graph
- config/migrations/2025/20250704104058-feat--add-agb-havenbedrijf-antwerpen.ttl
This organisation used to be in OP but was removed as it is not officially an administrative unit. But now the organisation needs access to the subsidiepunt app to finalise some of their subsidy requests.
Therefore we recreate this organisation with the original URI. This way they can login again to subsidiepunt once the data has flown through.
I manually created a new organisation via the frontend with the appropriate data (contact information, identifiers, etc.) Afterwards I extracted all relevant inserted this data and put this in a TTL migration. Finally, I replaced the URI generated for the administrative unit with the correct one.
This approach had the advantage that the frontend and other services do the heavy lifting of creating the right data (structures).
Follow the instructions …
> feat: re-add AGB Havenbedrijf Antwerpen

- CHANGELOG.md
- config/migrations/2025/20250708140355-fix-changeevent-dates.sparql
[OP-3559](https://binnenland.atlassian.net/browse/OP-3559)
Adds a migration that corrects inconsistent dcterms:date values used in org:ChangeEvent resources.
> Migration - harmonize date formats of change events

- CHANGELOG.md
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250707132349-chore--extract-scopes-for-worship-organisations.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250709140704-feat--set-scope-for-worship-organisations-with-single-location.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250709160017-feat--set-scope-for-worship-organisations-with-multiple-locations.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250710095207-chore--clear-temp-graph-worship-scopes.sparql
- scripts/project/config.json
- scripts/project/correct-location-labels/run.rb
Worship administrative units are so far not linked to a location as their scope of operation. Since this will become a mandatory field for administrative units, we already set some initial scope of operation for (central) worship services. This way users are not blocked from editing worship administrative units.
Business provided rules on which locations can be set as initial scope of operations. In general a worship administrative unit should be linked to locations matching a subset of it local involvements. The following table is adapted from the linked ticket. The first row, for example, means "for worship services of type Islamitisch or Orthodox, use the locations for the locally involvement advisory municipalities as scope of operation."
|                         | Types …
> feat: set initial scope of operation for worship administrative units

- CHANGELOG.md
- config/authorization/config.ex
- config/dispatcher/dispatcher.ex
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250707132349-chore--extract-scopes-for-worship-organisations.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250709140704-feat--set-scope-for-worship-organisations-with-single-location.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250709160017-feat--set-scope-for-worship-organisations-with-multiple-locations.sparql
- config/migrations/2025/20250707132349-feat--add-scope-for-operation-worship-organisations/20250710095207-chore--clear-temp-graph-worship-scopes.sparql
- config/resources/domain.json
- docker-compose.dev.yml
- docker-compose.yml
- scripts/project/config.json
- scripts/project/correct-location-labels/run.rb
The functionality of OP is extended to allow users to consult and edit the scope of operation (*nl. werkingsgebied*) for administrative units. This PR wires the new service written to support this functionality into OP's stack.
Previously, a location was only allowed to be `geo:sfWithin` one other location. As part of this PR the cardinality of this relation was changed to many. Otherwise some possible situations could not be modelled. For example, say an administrative unit `A` has as scope of operation the locations `One` and `Two`, or more precisely a location resources containing these two locations. Another administrative unit `B` has as scope of operation same location `One` as well as location `Three`. In this case it must be possible that `One` can be `geo:sfWithin` two different …
> feat: add scope-of-operation service

- CHANGELOG.md
- config/dev-migrations/20250708142100-fix-same-address-linked-to-both-site-and-contact-point.sparql
- config/migrations/2025/20250708142100-fix-same-address-linked-to-both-site-and-contact-point.sparql
- config/migrations/2025/20250722114200-fix-contact-addresses-being-in-wrong-graph.sparql
[DL-6701]
On dev, some addresses are linked both to sites and to contact point of mandatarissen. It doesn't make any sense and I couldn't trace it back to the source. The issue did not affect other environments.
The migration should fix it by creating a dupe of the affected addresses and by linking those dupes to the sites. That way, sites and contact points have independent addresses. We update the link between site and address and not between mandataris and address because OP is master of the sites, which means we should then produce the correct data and forward it to consuming apps.
> Add migration to fix dev addresses

- CHANGELOG.md
- config/migrations/2025/20250725120411-fix-reversed-memberships-ocmw-municipality.sparql
- config/migrations/2025/20250725120522-remove-duplicate-memberships-ocmw-municipality.sparql
OP-3634
Following the conclusion of the analysis (see ticket), the solution of the duplicate memberships should be to remove the inverse membership where the municipality is linked with `org:member` and the ocmw is linked with `org:organization`.
Using op dev data, the query should remove all the inverse/duplicate memberships. For example of 'gemeente affligem' it should only have 1 membership with 'ocmw affligem'. The same membership should show up for 'ocmw affligem' as well.
> add duplicate memberships cleanup migration
